# Generated by Django 5.2.7 on 2025-10-10 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.BinaryField()),
                ('face_image', models.ImageField(upload_to='unknown_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
