# Generated by Django 5.2.7 on 2025-10-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_unknownface'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to the captured image', max_length=500),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='pose',
            field=models.CharField(default='front', help_text='Pose: front, left, right, up, down', max_length=20),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='quality_metrics',
            field=models.JSONField(default=dict, help_text='Quality assessment metrics'),
        ),
    ]
